bundle.bbclass: drop obsolete clean before fetch
We have observed occasional errors during do_fetch:

ERROR: bundle-dev-1.0-r0 do_fetch: CalledProcessError(1, ['rm', '-rf', '[..]/build/tmp/work/x86-oe-linux/bruker-bundle-dev/1.0'])
ERROR: Task ([..]/recipes-core/bundles/bundle-dev.bb:do_fetch) failed with exit code '1'

The line in question is probably a remnant of

  f8f0589 classes: bundle: move manifest writing to do_unpack

which moved functionality from do_fetch to do_unpack

Signed-off-by: Torben Hohn <torben.hohn@bruker.com>
Signed-off-by: Thomas Albrecht <thomas.albrecht@bruker.com>
(cherry picked from commit b614931efa9d7f6ee09d3839766dc08bfe9b3953)
Signed-off-by: Enrico Jörns <ejo@pengutronix.de>