classes-recipe/bundle.bbclass: Fix UNPACKDIR
Remove WORKDIR and use UNPACKDIR to set S.

Fixes:

ERROR: update-bundle-1.0-r0 do_unpack: S should be set relative
to UNPACKDIR, e.g. replace WORKDIR with UNPACKDIR in
"S = ${WORKDIR}/sources"

Follows the migration manual update from yocto-docs rev e69144a2
"migration-guides/migration-5.1.rst: correct S/UNPACKDIR patterns for file-only recipes"

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
[dropped further UNPACKDIR -> S replacements]
Signed-off-by: Enrico Jörns <ejo@pengutronix.de>