bundle.bbclass: depend on an earlier task for images
This patch fixes build error reported below that popped up after
recent oe-core commits enabling RSS. Setting dependencies on images
to an earlier task (do_image_complete instead of do_build) was
suggested on IRC #yocto channel and seems to fix the build.

Without the patch the build fails complaining as follows:

ERROR: update-bundle-1.0-r0 do_prepare_recipe_sysroot: Error executing a python
function in exec_python_func() autogenerated:

The relevant stack trace was:

  File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
  File: '/home/gizero/work/smartliving/distro/repo-master/build-poky/conf/../../layers/poky/
  meta/classes/staging.bbclass',
  lineno: 592, function: extend_recipe_sysroot
  File: '/home/gizero/work/smartliving/distro/repo-master/build-poky/conf/../../layers/poky/
  meta/classes/staging.bbclass',
  lineno: 233, function: staging_copyfile
  Exception: FileExistsError: [Errno 17] File exists:
  '/home/gizero/work/smartliving/distro/repo-master/build-poky/tmp/sysroots-components/
  cortexa7hf-neon-vfpv4/libgcc/usr/lib/arm-poky-linux-gnueabi/6.3.0/c
  rtfastmath.o' -> '/home/gizero/work/smartliving/distro/repo-master/build-poky/tmp/work/
  raspberrypi3-poky-linux-gnueabi/update-bundle/1.0-r0/recipe-sysroot/usr/lib/
  arm-poky-linux-gnueabi/6.3.0/crtfastmath.o'

Signed-off-by: Andrea Galbusera <gizero@gmail.com>