rauc: add patch for openssl 4.0 compatibility
This patch is backported from a rauc pull request[1] that has been merged,
but did not make it into a release yet.

This avoids build errors like the following:

    error: invalid use of incomplete typedef ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}

[1]: https://github.com/rauc/rauc/pull/1914

Signed-off-by: Leonard Göhrs <l.goehrs@pengutronix.de>