rauc-git.inc: Remove S = "${WORKDIR}/git"
Remove the assignment S = "${WORKDIR}/git" following the recent
change in openembedded-core:
https://git.openembedded.org/openembedded-core/commit/?id=46480a5e66747a673041fe4452a0ab14a1736d5e

Fixes:

ERROR: rauc-1.14+git-r0 do_unpack: Recipes that set
S = "${WORKDIR}/git" or S = "${UNPACKDIR}/git" should remove that
assignment, as S set by bitbake.conf in oe-core now works.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>