conf/layer.conf: Support Blacksail
Set the layer compatibility to the Yocto Project release Blacksail
following the recent change in openembedded-core:
https://git.openembedded.org/openembedded-core/commit/?id=37623ffbdd34a5c6b3e12ee33195f8e82343f198

Fixes:

ERROR: Layer rauc is not compatible with the core layer which only
supports these series: blacksail (layer is compatible with wrynose)

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>